baseURL = ''
languageCode = 'en-us'
title = 'SpaceCamp'
theme = 'digitalgarden'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.social]]
    name = 'GitHub'
    url = 'https://github.com/chnm/spacecamp'
    weight = 1
[[menu.social]]
    name = 'Twitter'
    url = 'https://twitter.com/chnm'
    weight = 2
